services:
  - type: web
    name: installsystem
    env: python

    buildCommand: pip install -r requirements.txt && python manage.py migrate

    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
